### ISSUE TITLE
NFVM Instances

### ISSUE THREAD

**Issue by 1995parham** [roadtomsc/simulation#14]
Sometimes solver places unused VNFM instances on physical nodes. There is no restriction on this based on my current mathematical model so I think its correct behavior but @behroozfarkiani do you consider it bad behavior?

**Comment by 1995parham** [comment]
The number of VNFM instances on each physical node is controlled by `y_hat` an `y_hat` is limited by physical node resources. At least `y_hat * vnfm_capacity` must be greater than `instances_that_are_managed_by_physical_node_w`.

**Comment by behroozfarkiani** [comment]
Thats okey.

**Comment by behroozfarkiani** [comment]
If you check your solution, you will see not optimal paths (contain loop for instanse). It is okey to have such conditions because they don't violate neither optimality not feasiblity.

**Comment by 1995parham** [comment]
Thanks, Doc! 🙌
