### ISSUE TITLE
Desing another solution methodology

### ISSUE THREAD

**Issue by behroozfarkiani** [roadtomsc/simulation#4]
So far, you have the motivations of why you considered the manager constraints at the same time with the VNF placement (illustrative example), a motivation for designing another solution methodology (motivating example). So, now you can design another solution methodology to overcome the difficulty. 

Describe the objective of your solution methodology (that is the difficulty(s)). Analyze the motivating example and design something!

**Comment by 1995parham** [comment]
@behroozfarkiani As you know I have implemented a simple heuristic approach for my problem many months ago, I want to complete its basis in the meanwhile I am trying to solve and report my exact solution. You can find the repository [here](https://github.com/roadtomsc/Marhoom).
