### ISSUE TITLE
motivating to not solve the problem directly

### ISSUE THREAD

**Issue by behroozfarkiani** [roadtomsc/simulation#5]
Use a large topology (more than 30 servers, 40 switches, and multiple ingress/egress points) to find a point that is too expensive to solve the problem directly using ILP solvers.  For instance, it may take a long time (more than 0.5 hours) or it requires a huge amount of memory or the solver failed to solve it. 

You can use the following specs
![image](https://user-images.githubusercontent.com/11196143/55336545-534d5680-54b2-11e9-9593-30c0f2af22d7.png)

Implement the example, describe the difficulty you have encountered.

**Comment by 1995parham** [comment]
@behroozfarkiani I have used the 4-ary fat-tree as my large example. You can find out more about it [here](https://github.com/roadtomsc/FatTree). Do you consider it okay? I have created the topology file [here](https://github.com/roadtomsc/simulation/blob/master/config/topology.yaml) and I have tested it with small numbers of chains.

**Comment by 1995parham** [comment]
@behroozfarkiani I have tested the simulation and gathered the results [here](). What do you think? I want to reduce the memory consumption and solve the problem in a better time with an answer that might be 3-time worst than the optimal result.
